version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
  - package_manager: "python"
    directory: "/docs"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
  - package_manager: "python"
    directory: "/.github/workflows"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
