name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt nox poetry
      - run: nox --force-color --session=tests-3.8 -- --cov --cov-report=xml
      - if: always()
        uses: codecov/codecov-action@v1.0.7
