name: Labeler

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.3

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          dry-run: false
          exclude: |
            hacktoberfest*
