name: Release Drafter
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.17.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
