name: Update cookiecutter-hypermodern-python-instance
on:
  push:
    branches:
      - master
jobs:
  instance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out cookiecutter-hypermodern-python
        uses: actions/checkout@v2.3.4
        with:
          path: cookiecutter-hypermodern-python
      - name: Check out cookiecutter-hypermodern-python-instance
        uses: actions/checkout@v2.3.4
        with:
          repository: "cjolowicz/cookiecutter-hypermodern-python-instance"
          path: cookiecutter-hypermodern-python-instance
          token: ${{ secrets.X_GITHUB_TOKEN }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.1
        with:
          python-version: "3.9"
      - name: Upgrade pip
        working-directory: cookiecutter-hypermodern-python
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
      - name: Install cruft
        working-directory: cookiecutter-hypermodern-python
        run: |
          pip install --constraint=.github/workflows/constraints.txt cruft
      - name: Update cookiecutter-hypermodern-python-instance
        working-directory: cookiecutter-hypermodern-python-instance
        run: |
          cruft update -y --checkout=$GITHUB_SHA
      - name: Check that no changes were rejected
        working-directory: cookiecutter-hypermodern-python-instance
        run: |
          if [ $(find . -name '*.rej' | wc -l) -gt 0 ]
          then
              exit 1
          fi
      - name: Reformat .cruft.json
        working-directory: cookiecutter-hypermodern-python-instance
        shell: python
        run: |
          import json
          from pathlib import Path

          path = Path(".cruft.json")
          text = path.read_text()
          data = json.loads(text)

          # Prettier wants two spaces for indentation and a final newline.
          text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
          path.write_text(text)
      - name: Determine commit information
        working-directory: cookiecutter-hypermodern-python
        run: |
          git show --no-patch --format="\
          GIT_AUTHOR_NAME=%an
          GIT_AUTHOR_EMAIL=%ae
          GIT_AUTHOR_DATE=%ad
          GIT_COMMITTER_NAME=GitHub Action
          GIT_COMMITTER_EMAIL=action@github.com
          MESSAGE<<EOF
          %B

          Original-Commit: ${GITHUB_REPOSITORY}@${GITHUB_SHA::7}"
          EOF" | sed 's/ *(#[0-9]\+)//g' >> $GITHUB_ENV
      - name: Create commit
        working-directory: cookiecutter-hypermodern-python-instance
        run: |
          git add .
          git commit --allow-empty --message="$MESSAGE"
      - name: Push to instance
        working-directory: cookiecutter-hypermodern-python-instance
        run: >-
          git push
          https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/cjolowicz/cookiecutter-hypermodern-python-instance.git
          HEAD:master
